// Code generated by hertz generator.

package user

import (
	"hertz_template/biz/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _userMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.AccessLog(),
	}
}

func _createuserMw() []app.HandlerFunc {
	return nil
}

func _deleteMw() []app.HandlerFunc {
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	return nil
}

func _updateMw() []app.HandlerFunc {
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	return nil
}

func _userloginMw() []app.HandlerFunc {
	return nil
}

func _userlistMw() []app.HandlerFunc {
	return nil
}

func _change_passwdMw() []app.HandlerFunc {
	return nil
}

func _changepasswdMw() []app.HandlerFunc {
	return nil
}

func _infoMw() []app.HandlerFunc {
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	return nil
}
