// Code generated by hertz generator.

package book

import (
	"github.com/cloudwego/hertz/pkg/app"
	"hertz_template/biz/mw"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _apiMw() []app.HandlerFunc {
	return nil
}

func _bookMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.AccessLog(),
	}
}

func _createbookMw() []app.HandlerFunc {
	return nil
}

func _booklistMw() []app.HandlerFunc {
	return nil
}

func _deleteMw() []app.HandlerFunc {
	return nil
}

func _deletebookMw() []app.HandlerFunc {
	return nil
}

func _updateMw() []app.HandlerFunc {
	return nil
}

func _updatebookMw() []app.HandlerFunc {
	return nil
}
